services:
  chopper:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chopper-dev
    runtime: nvidia    volumes:
      - .:/ros_ws
    environment:
      - ROS_DOMAIN_ID=42
      - DISPLAY=host.docker.internal:0
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyTHS1:/dev/ttyTHS1"    stdin_open: true
    tty: true
